### ISSUE TITLE
Not an issue. Can we post media with this tool?

### ISSUE THREAD

**Issue by mobilelifeful** [trozman/Tweetbotty#2]
Thank you for sharing this tool. Wonder if we can post media with this tool?

**Comment by trozman** [comment]
Sorry, not yet. Thanks for the suggestion.

**Comment by trozman** [comment]
Yes, now you can post

**Comment by trozman** [comment]
Yes, now you can post media along with the tweets. 
Just put images (jp, png, animated gifs) in /tw_pics subfolder and reference them in the Tweets.xlsx file, Column F.
If an image exists, it will be added to your twit.
